# Generated by Django 5.2.4 on 2025-07-28 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobhub', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='website',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
